name: choose_app
description: App that brings a unique solution to the age-old problem of decision making.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # General
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_hooks: ^0.18.6

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Dependency injection
  injectable: ^2.1.2
  get_it: ^7.6.0

  # Routing
  auto_route: ^7.7.0

  # UI
  flutter_native_splash: ^2.3.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0


dev_dependencies:

  # Code generation
  injectable_generator: ^2.1.6
  build_runner: ^2.4.6
  auto_route_generator: ^7.2.0
  json_serializable: ^6.7.1

  # Testing
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.2
  mocktail: ^0.3.0

  # Linting
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
